kind: pipeline
type: docker
name: backend

platform:
  os: linux
  arch: amd64

steps:
  - name: test
    image: maven:3.8.3-openjdk-17
    commands:
      - mvn test
      - mvn clean install
  - name: test
    image: maven:3.8.3-openjdk-17
    commands:
      - mvn test
      - mvn clean install

trigger:
  event:
    - push
    - pull_request