kind: pipeline
type: docker
name: backend

platform:
  os: linux
  arch: amd64

steps:
  - name: greeting
    image: alpine
    commands:
      - echo hello world
  - name: build
    image: maven:3.8.3-openjdk-17
    commands:
      - mvn clean install
      - java -jar target/basic-app.jar

trigger:
  event:
    - push
    - pull_request