kind: pipeline
type: docker
name: backend

platform:
  os: linux
  arch: amd64

steps:
  - name: maven_test
    image: maven:3.8.3-openjdk-17
    commands:
      - mvn test

  - name: maven_build
    image: maven:3.8.3-openjdk-17
    commands:
      - mvn clean package

  - name: docker_build
    image: docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build -t basic-app .
    depends_on:
      - maven_test
      - maven_build

trigger:
  event:
    - push
    - pull_request