kind: pipeline
type: docker
name: backend

platform:
  os: linux
  arch: amd64

steps:
  - name: test
    image: maven:3.8.3-openjdk-17
    commands:
      - mvn test
  - name: build
    image: maven:3.8.3-openjdk-17
    commands:
      - mvn clean package
  - name: publish
    image: docker
    commands:
      - docker build -t basic-app .
    depends_on:
      - test
      - build

trigger:
  event:
    - push
    - pull_request