kind: pipeline
type: docker
name: backend-app

platform:
  os: linux
  arch: amd64

steps:
  - name: test
    image: maven:3.8.3-openjdk-17
    commands:
      - mvn test
  - name: build
    image: maven:3.8.3-openjdk-17
    commands:
      - mvn clean package
    depends_on:
      - test
  - name: publish
    commands:
      - docker build -t basic-app .

trigger:
  event:
    - push
    - pull_request